# Generated by Django 5.2.16 on 2026-07-16 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('puzzles', '0002_seed_motif_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeaknessSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('occurrences_in_window', models.PositiveIntegerField()),
                ('games_in_window', models.PositiveIntegerField()),
                ('attempts', models.PositiveIntegerField()),
                ('correct', models.PositiveIntegerField()),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzles.motiftag')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('date', 'tag'), name='unique_snapshot_per_date_tag')],
            },
        ),
    ]
