# Generated by Django 5.2.16 on 2026-07-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chesscom_uuid', models.CharField(max_length=64, unique=True)),
                ('url', models.URLField()),
                ('pgn', models.TextField()),
                ('end_time', models.DateTimeField(db_index=True)),
                ('time_class', models.CharField(choices=[('bullet', 'Bullet'), ('blitz', 'Blitz'), ('rapid', 'Rapid'), ('daily', 'Daily')], max_length=10)),
                ('time_control', models.CharField(max_length=20)),
                ('rated', models.BooleanField(default=True)),
                ('user_color', models.CharField(max_length=5)),
                ('user_rating', models.PositiveIntegerField()),
                ('opponent_username', models.CharField(max_length=50)),
                ('opponent_rating', models.PositiveIntegerField()),
                ('result', models.CharField(max_length=10)),
                ('eco', models.CharField(blank=True, max_length=3)),
                ('opening_name', models.CharField(blank=True, max_length=120)),
                ('analysis_status', models.CharField(choices=[('pending', 'Pending'), ('analyzed', 'Analyzed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10)),
                ('analysis_failures', models.PositiveSmallIntegerField(default=0)),
                ('analysis_error', models.TextField(blank=True)),
                ('engine_version', models.CharField(blank=True, max_length=40)),
                ('engine_movetime_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('pipeline_version', models.CharField(blank=True, max_length=20)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-end_time'],
            },
        ),
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='running', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('counts', models.JSONField(default=dict)),
                ('error_text', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
