# Generated by Django 5.2.16 on 2026-07-16 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotifTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=60)),
                ('tier', models.IntegerField(choices=[(1, 'Rule'), (2, 'Fuzzy')])),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fen', models.CharField(max_length=100)),
                ('position_key', models.CharField(max_length=64, unique=True)),
                ('puzzle_type', models.CharField(choices=[('avoid', 'Avoid'), ('punish', 'Punish')], max_length=6)),
                ('direction', models.CharField(choices=[('missed', 'Missed'), ('allowed', 'Allowed'), ('miscounted', 'Miscounted')], max_length=10)),
                ('win_pct_before', models.FloatField()),
                ('solutions', models.JSONField()),
                ('uniqueness_gap_wp', models.FloatField()),
                ('shallow_depth_stable', models.BooleanField()),
                ('shallow_depth_used', models.PositiveSmallIntegerField()),
                ('cashout_plies', models.PositiveSmallIntegerField()),
                ('mate_in', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('engine_version', models.CharField(blank=True, max_length=40)),
                ('engine_movetime_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('phase', models.CharField(choices=[('opening', 'Opening'), ('middlegame', 'Middlegame'), ('endgame', 'Endgame')], max_length=10)),
                ('is_opening_leak', models.BooleanField(default=False)),
                ('quality_score', models.FloatField(db_index=True)),
                ('explanation', models.TextField(blank=True)),
                ('explanation_model', models.CharField(blank=True, max_length=60)),
                ('tagged_at', models.DateTimeField(blank=True, null=True)),
                ('tag_attempts', models.PositiveSmallIntegerField(default=0)),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('interval_days', models.FloatField(default=0)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('repetitions', models.PositiveIntegerField(default=0)),
                ('lapses', models.PositiveIntegerField(default=0)),
                ('buried_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PuzzleMotif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('rule', 'Rule'), ('llm', 'Llm')], max_length=4)),
                ('confidence', models.FloatField(default=1.0)),
                ('rule_verified', models.BooleanField(null=True)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzles.puzzle')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzles.motiftag')),
            ],
        ),
        migrations.AddField(
            model_name='puzzle',
            name='motifs',
            field=models.ManyToManyField(blank=True, through='puzzles.PuzzleMotif', to='puzzles.motiftag'),
        ),
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ply', models.PositiveIntegerField()),
                ('played_uci', models.CharField(max_length=6)),
                ('played_san', models.CharField(max_length=10)),
                ('win_pct_after_played', models.FloatField()),
                ('clock_seconds', models.FloatField(blank=True, null=True)),
                ('clock_bucket', models.CharField(blank=True, choices=[('comfortable', 'Comfortable'), ('low', 'Low'), ('scramble', 'Scramble')], default='', max_length=12)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='games.game')),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='puzzles.puzzle')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('game', 'ply'), name='unique_occurrence_per_game_ply')],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ply', models.PositiveIntegerField()),
                ('position_key', models.CharField(db_index=True, max_length=64)),
                ('fen', models.CharField(max_length=100)),
                ('candidate_type', models.CharField(max_length=6)),
                ('played_uci', models.CharField(max_length=6)),
                ('played_san', models.CharField(max_length=10)),
                ('win_pct_before', models.FloatField()),
                ('win_pct_after_played', models.FloatField()),
                ('clock_seconds', models.FloatField(blank=True, null=True)),
                ('uniqueness_gap_wp', models.FloatField(blank=True, null=True)),
                ('shallow_depth_stable', models.BooleanField(null=True)),
                ('shallow_depth_used', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cashout_plies', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('legal_move_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('verdict', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=8)),
                ('rejection_gate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='games.game')),
                ('puzzle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='puzzles.puzzle')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('game', 'ply'), name='unique_candidate_per_game_ply')],
            },
        ),
        migrations.AddConstraint(
            model_name='puzzlemotif',
            constraint=models.UniqueConstraint(fields=('puzzle', 'tag'), name='unique_motif_per_puzzle'),
        ),
        migrations.AddIndex(
            model_name='puzzle',
            index=models.Index(fields=['puzzle_type', 'phase'], name='puzzles_puz_puzzle__8939eb_idx'),
        ),
        migrations.AddIndex(
            model_name='puzzle',
            index=models.Index(fields=['due_at', '-quality_score'], name='puzzles_puz_due_at_9b7118_idx'),
        ),
    ]
