# Generated by Django 5.2.16 on 2026-07-16 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('puzzles', '0002_seed_motif_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moves', models.JSONField(default=list)),
                ('correct', models.BooleanField()),
                ('failed_at_ply', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('hints_used', models.PositiveSmallIntegerField(default=0)),
                ('grade', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='puzzles.puzzle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='puzzles.puzzle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
